### PR TITLE
add black to pre-commit and github actions

### LINKED ISSUE #57: Automate black formatting with github action
In #55 @michaelbornholdt noticed that `black` was making unanticipated changes, and I thought that it could be some version difference.

To make it consistent (and to avoid these confusions in the future), we should add an auto-black github action: https://github.com/psf/black/actions/runs/17913292/workflow

### PR DESCRIPTION
**Pull request by alxndrkalinin**
closes #57 

This PR:
* adds black config `black.toml`
* makes black run locally on commit via [`pre-commit`](https://pre-commit.com/)
* adds black to github actions

### CODE REVIEW

**Comment by alxndrkalinin** [comment]
Another suggestion is to also add [flake8](https://flake8.pycqa.org/en/latest/) to enforce style (e.g. unused imports, missing docstrings), etc.

**Review by gwaybio — APPROVED** [review]
Looks great!

Flake8 is a nice idea, but it seems to be python version specific. Since we support multiple versions  >=3.5, wouldn't this cause issues?

**Comment by alxndrkalinin** [comment]
@gwaybio
Finally back to this. I tested linting with flake8 under python versions 3.5-3.9 and the requirements seem consistent.

New changes make code flake8-compliant – mostly removing unused imports, variables, etc. It's not checking for docstring formatting, because it produces a ton of small issues – like only single-line docstring is allowed at the top of the file – I'm not sure are that important at this point.

**Review by gwaybio — APPROVED** [review]
LGTM 👍

**Pull request merged**
